on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest 
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: mediatek.formation.go.yj.fr
        server-dir: /www/mediatekformation/
        username: szpcchzj
        password: ${{ secrets.ftp_password }}
